apiVersion: v2
name: vigil
description: Vigil SOC — open-source, AI-native Security Operations Center
type: application
version: 0.4.1
appVersion: 0.4.1
kubeVersion: '>=1.25.0-0'
home: https://github.com/Vigil-SOC/vigil
sources:
  - https://github.com/Vigil-SOC/vigil
maintainers:
  - name: Vigil-SOC
    url: https://github.com/Vigil-SOC
keywords:
  - security
  - soc
  - siem
  - ai
  - claude
  - anthropic
  - mcp
icon: https://raw.githubusercontent.com/Vigil-SOC/vigil/main/docs/logo.png
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
dependencies:
  - name: postgresql
    version: 16.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.bitnami.enabled
    import-values:
      - child: auth
        parent: postgresql.bitnami.auth
  - name: redis
    version: 20.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.bitnami.enabled
  - name: opentelemetry-collector
    version: 0.108.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: otelCollector.enabled
    alias: otelCollector
